# Generated by Django 5.1.4 on 2024-12-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0005_remove_consultation_resume_dpi_qr_code_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='qrcodes/'),
        ),
    ]
