# Generated by Django 5.1.4 on 2024-12-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0006_alter_dpi_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='codeQR',
        ),
    ]
