# Generated by Django 5.1.4 on 2024-12-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0007_remove_patient_codeqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='antecedents',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dpi',
            name='qr_code',
            field=models.ImageField(default=1, unique=True, upload_to='qrcodes/'),
        ),
    ]
