# Generated by Django 5.1.4 on 2024-12-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiondpi', '0008_alter_dpi_antecedents_alter_dpi_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dpi',
            name='qr_code',
            field=models.ImageField(unique=True, upload_to='qrcodes/'),
        ),
    ]
